// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBilCEJFkX16ZkmVKq6ejFFr2PRF-4SWyU',
    appId: '1:482778771643:web:2071be2f9fcd80c206399e',
    messagingSenderId: '482778771643',
    projectId: 'todolistnv-ba6f2',
    authDomain: 'todolistnv-ba6f2.firebaseapp.com',
    storageBucket: 'todolistnv-ba6f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABjk7vp8oUDvUoBJf1SFAFjoNChIVlw0M',
    appId: '1:482778771643:android:c2ec04d6a00e7fd806399e',
    messagingSenderId: '482778771643',
    projectId: 'todolistnv-ba6f2',
    storageBucket: 'todolistnv-ba6f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbRuFrG_3zLtG0GHoalOwPYzf13k0Mclw',
    appId: '1:482778771643:ios:a3b705eddad16f2606399e',
    messagingSenderId: '482778771643',
    projectId: 'todolistnv-ba6f2',
    storageBucket: 'todolistnv-ba6f2.appspot.com',
    iosBundleId: 'com.example.listtodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbRuFrG_3zLtG0GHoalOwPYzf13k0Mclw',
    appId: '1:482778771643:ios:a3b705eddad16f2606399e',
    messagingSenderId: '482778771643',
    projectId: 'todolistnv-ba6f2',
    storageBucket: 'todolistnv-ba6f2.appspot.com',
    iosBundleId: 'com.example.listtodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBilCEJFkX16ZkmVKq6ejFFr2PRF-4SWyU',
    appId: '1:482778771643:web:d31e35ce289e73d406399e',
    messagingSenderId: '482778771643',
    projectId: 'todolistnv-ba6f2',
    authDomain: 'todolistnv-ba6f2.firebaseapp.com',
    storageBucket: 'todolistnv-ba6f2.appspot.com',
  );
}
